### ISSUE TITLE
通过环境变量预设LLM的baseurl和key

### ISSUE THREAD

**Issue by ycz87** [PDFMathTranslate/PDFMathTranslate-next#53]
### 在什么场景下，需要你请求的功能？

能否增加功能，实现通过环境变量预设LLM的baseurl和key，并在界面隐藏相关信息。

**Comment by senshinya** [comment]
通过 docker 部署时，设置环境变量似乎无效，还是需要在 gui 上手动填写

**Comment by awwaawwa** [comment]
> 通过 docker 部署时，设置环境变量似乎无效，还是需要在 gui 上手动填写

请给出完整复现流程

**Comment by senshinya** [comment]
> 请给出完整复现流程

docker compose：

```yaml
services:
  pdf2zh:
    image: awwaawwa/pdfmathtranslate-next
    env_file: .env
    ports:
      - 7860:7860
    restart: unless-stopped
```

.env

```
DEEPLX_ENDPOINT=https://api.deeplx.org/xxxx/translate
OPENAILIKED_BASE_URL=https://xxxx/api
OPENAILIKED_API_KEY=sk-xxxxxxx
OPENAILIKED_MODEL=gpt-4.1-mini
```

启动后访问 gui，选择 OpenAI 后

<img width="517" height="434" alt="Image" src="https://github.com/user-attachments/assets/83ccb155-16ba-42cb-8816-760cee61903f" />

提交报错：Error Invalid settings: OpenAI API key is required
